import {describe} from "mocha";

const path = require("path");
const wasm_tester = require("circom_tester").wasm;

// inputs MUST be generated by GO-CIRCUITS library https://github.com/iden3/go-circuits (using corresponding test)
describe("idUtils.circom:", async function() {
    
    const tests = [
        {
            desc: "First",
            input: {
                in: "13843376158434186874150155371608112991467708075683980446964675987616037973262",
            },
            output: {
                out: "12590477270745565760216918871818154904274440992307045641577748017",
            },
        },
    ];

    let circuit;
    this.timeout(300000)

    before(async () => {
        circuit = await wasm_tester(
            path.join(__dirname, "../circuits", "idUtils_ShiftRight.circom"),
            {
                output: path.join(__dirname, "../circuits", "build/idUtils_ShiftRight"),
                recompile: true,
                reduceConstraints: true,
            },
        );
    });

    tests.forEach(({desc, input, output}) => {
        it(`auth ${desc}`, async function() {
            const w = await circuit.calculateWitness(input, true);
            await circuit.checkConstraints(w);
            await circuit.assertOut(w, output);
        });
    });
});
