import {describe} from "mocha";

const path = require("path");
const wasm_tester = require("circom_tester").wasm;

// inputs MUST be generated by GO-CIRCUITS library https://github.com/iden3/go-circuits (using corresponding test)
describe("idUtils.circom:", async function() {
    
    const tests = [
        {
            desc: "First",
            input: {
                typ: "49648",
                genesis: "12590477270745565760216918871818154904274440992307045641577748017",
            },
            output: {
                out: "4565",
            },
        },
        {
            desc: "Max values",
            input: {
                typ: "65535", // 0xffff
                // 0xffffffffffffffffffffffffffffffffffffffffffffffffffffff
                genesis: "105312291668557186697918027683670432318895095400549111254310977535",
            },
            output: {
                out: "7395", // 0x1CE3 - max checksum value possible
            },
        },
    ];

    let circuit;
    this.timeout(300000)

    before(async () => {
        circuit = await wasm_tester(
            path.join(__dirname, "../circuits", "idUtils_CalculateIdChecksum.circom"),
            {
                output: path.join(__dirname, "../circuits", "build/idUtils_CalculateIdChecksum"),
                recompile: true,
                reduceConstraints: true,
            },
        );
    });

    tests.forEach(({desc, input, output}) => {
        it(`CalculateIdChecksum - ${desc}`, async function() {
            const w = await circuit.calculateWitness(input, true);
            await circuit.checkConstraints(w);
            await circuit.assertOut(w, output);
        });
    });
});
