import {describe} from "mocha";

const path = require("path");
const wasm_tester = require("circom_tester").wasm;

// inputs MUST be generated by GO-CIRCUITS library https://github.com/iden3/go-circuits (using corresponding test)
describe("idUtils.circom:", async function() {

    const tests = [
        {
            desc: "Salted hash",
            input: {
                in: "379949150130214723420589610911161895495647789006649785264738141299135414272", //379949150130214723420589610911161895495647789006649785264738141299135414272
                salt: "10",
            },
            output: {
                out: "86673097869291892577577670655095803058458914610818194234435166934839525376",
            },
        },
        {
            desc: "Salted hash",
            input: {
                in: "415299404698947339257583884918951054741692084831172369057254226634366386176", //379949150130214723420589610911161895495647789006649785264738141299135414272
                salt: "10",
            },
            output: {
                out: "74283886503142965875513788535494945852492977609287320056134303119186395136",
            },
        }
    ];

    let circuit;
    this.timeout(300000)

    before(async () => {
        circuit = await wasm_tester(
            path.join(__dirname, "../circuits", "idUtils_ProfileID2.circom"),
            {
                output: path.join(__dirname, "../circuits", "build/idUtils_ProfileID2"),
                recompile: true,
                reduceConstraints: true,
            },
        );
    });

    tests.forEach(({desc, input, output}) => {
        it(`auth ${desc}`, async function() {
            const w = await circuit.calculateWitness(input, true);
            await circuit.checkConstraints(w);
            await circuit.assertOut(w, output);
        });
    });
});
